In [1]:
# imports
import pandas as pd

In [6]:
# reading in csvs
bb2021 = pd.read_csv('../data/newbb21.csv')
bbTo20 = pd.read_csv('../data/bb2020BetterCols.csv')
tracks = pd.read_csv('../data/tracks_cleanedAbbrev.csv')

In [7]:
# showing csvs as dfs
bb2021.head()

,song,performer,date,chart_position,previous_position,peak,weeks_on_chart,hitTF
0,Kings & Queens,Ava Max,2021-01-02,41,30,15,8,1
1,Champagne Night,Lady A,2021-01-02,80,0,33,6,1
2,Cry Baby,Megan Thee Stallion Featuring DaBaby,2021-01-02,67,95,28,18,1
3,Body,Megan Thee Stallion,2021-01-02,35,22,16,16,1
4,Last Christmas,Wham!,2021-01-02,9,14,9,1,1

In [8]:
# showing csvs as dfs
bbTo20.head()

,song,performer,date,chart_position,previous_position,peak,weeks_on_chart,hitTF
0,Dance Monkey,Tones And I,2019-12-07,11,19,11,8,1
1,Pray For Me,The Weeknd & Kendrick Lamar,2018-04-07,12,10,7,8,1
2,Into The Unknown,Idina Menzel & AURORA,2019-12-07,55,0,55,1,1
3,Mine,Bazzi,2018-02-03,56,0,56,1,1
4,Indica Badu,Logic Featuring Wiz Khalifa,2018-03-24,56,0,56,1,1

In [9]:
# showing csvs as dfs
tracks.head()

,name,popularity,duration_ms,explicit,artists,release_date,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,hitTF
0,A Lover's Concerto,41,159560,0,The Toys,3/13/2020,0.671,0.867,2,-2.706,1,0.0571,0.436,0.000000,0.1390,0.839,120.689,4,0
1,The September Of My Years - Live At The Sands ...,26,187333,0,Frank Sinatra,5/4/2018,0.319,0.201,7,-17.796,1,0.0623,0.887,0.000000,0.9040,0.239,117.153,3,0
2,It Was A Very Good Year - Live At The Sands Ho...,25,236800,0,Frank Sinatra,5/4/2018,0.269,0.129,7,-18.168,0,0.0576,0.938,0.000005,0.6830,0.160,82.332,3,0
3,"The Circle Game - Live at The 2nd Fret, Philad...",18,313093,0,Joni Mitchell,10/30/2020,0.644,0.212,11,-14.118,1,0.0347,0.881,0.000022,0.7980,0.441,117.072,3,0
4,"Urge For Going - Live at The 2nd Fret, Philade...",18,295093,0,Joni Mitchell,10/30/2020,0.627,0.184,1,-15.533,1,0.0450,0.955,0.000162,0.0986,0.299,115.864,4,0

In [6]:
tracks.shape

(121426, 19)

In [7]:
# ! at this stage, could add the spotify ids, song attribute cols to the different dfs

In [10]:
# concatting the two bb dfs
allbbs = pd.concat([bbTo20, bb2021]).reset_index(drop=True)
allbbs.head()

,song,performer,date,chart_position,previous_position,peak,weeks_on_chart,hitTF
0,Dance Monkey,Tones And I,2019-12-07,11,19,11,8,1
1,Pray For Me,The Weeknd & Kendrick Lamar,2018-04-07,12,10,7,8,1
2,Into The Unknown,Idina Menzel & AURORA,2019-12-07,55,0,55,1,1
3,Mine,Bazzi,2018-02-03,56,0,56,1,1
4,Indica Badu,Logic Featuring Wiz Khalifa,2018-03-24,56,0,56,1,1

In [10]:
# code in progress: using currently theoretical cols in the dfs
# make sure that the spotify ID col is correctly named here
hitIDs = allbbs['spotifID'] 
updatedhitTF = []
for x in range(0, len(tracks)):
#     this is assuming that the spotifID col is the rightmost (as of right now) one in the df, ie with index 19
    if tracks.iloc[x, 19] in hitIDs:
        updatedhitTF.append[1]
    else:
        updatedhitTF.append(0)

tracks['hitTF'] = updatedhitTF
tracks.head()

KeyError: 'spotifID'

In [ ]:
# doing the outer join
# remember to use the proper spotify id col name
all_tracks_dataset = pd.merge(allbbs, tracks, on='spotifID', how='outer')
# the non-hit ones would be lacking values in 'date' and 'chart_position' cols
# for the former, the nonsense date 1/1/1900 can be used
# for the later, 0s can be used
all_tracks_dataset = all_tracks_dataset.fillna({'date': 1/1/1900, 'chart_position': 0})
all_tracks_dataset.head()